images:
  - name: repository-project/application:1.0.0  #used for Kustomize matching
    newName: samarsinghal/spring-petclinic
    newTag: latest
# configMapGenerator:
#   - name: spring-configmap  # naming convention in base use to mount the file to /config/application.properties in a persistent volume
#     files:
#       - application/application.properties
#   - name: spring-configmap-env  # naming convention in base to load environment variables from a reference to this config map
#     envs:
#       - application/env.properties
resources:
  - buildService/image.yaml                 
  - ../base
  - application/application-ingress.yaml
  - cd/argocd-app.yaml
  - ci/task.yaml
  - ci/pipeline.yaml                         
  - ci/serviceaccount.yaml        
  - ci/trigger-template.yaml
  - ci/eventlistener.yaml         
  - ci/ingress-event-listner.yaml 
# patches:
# - application/deployment-patch.yaml