
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-argo
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: kubernetes/overlays/dev/cd/resources
    repoURL: https://github.com/samarsinghal/spring-petclinic-app.git
    targetRevision: HEAD
    # directory:
    #   recurse: true
    #   jsonnet: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true