---
actions:
  to: kubernetes/overlays/dev/ci/eventlistener.yaml
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: harbor-listener-interceptor
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-github-triggers
  triggers:
  - name: harbor-listener
    # interceptors:
    # - github:
    #     secretRef:
    #       secretName: github-trigger-secret
    #       secretKey: secretToken
    #     eventTypes:
    #     - push
    # - cel:
    #     filter: "body.ref == 'refs/heads/tekton-testing'"
    bindings:
    - ref: build-deploy-binding
    template:
      ref: build-deploy-template
---
