---
actions:
  to: kubernetes/overlays/dev/ci/task.yaml
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
  namespace: tekton-pipelines
spec:
  params:
  - name: environment
  - name: argoAppName
  - name: configGitUrl
  - name: appImage
  - name: imageDigest
  workspaces:
  - name: config-source
  stepTemplate:
    # envFrom:
    # - secretRef:
    #     name: argocd-env-secret
    # env:
    # - name: ARGOCD_SERVER
    #   value: argocd-server.argocd

  steps:
  - name: git-checkout
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.config-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e

      # eval $(ssh-agent)
      # ssh-add ~/.ssh/id_*
      # git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=accept-new'
      # git init
      # git remote add origin $(params.configGitUrl)
      # git fetch --depth 1 origin master
      # git checkout master
      rm -rf spring-petclinic-app
      git clone $(params.configGitUrl) 

  # - name: update-yaml
  #   image: alpine/git:v2.26.2
  #   workingDir: "$(workspaces.config-source.path)"
  #   script: |
  #     #!/usr/bin/env sh
  #     set -e
  #     cd spring-petclinic-app/kubernetes/overlays/$(inputs.params.environment)/cd/resources

  #     echo "updating $(inputs.params.environment) image to $(inputs.params.appImage):$(inputs.params.imageDigest)"
  #     # sed -i "s#$(inputs.params.appImage):[a-zA-Z0-9]\\+#$(inputs.params.appImage):$(inputs.params.imageDigest)#" coffee-shop.yaml
  #     pwd 
  #     ls
  #     sed -i "s#newTag:[a-zA-Z0-9]\\+#newTag:$(inputs.params.imageDigest)#" kustomization.yaml
  #     cat kustomization.yaml
  #     # echo "updating all pods in $(inputs.params.environment) to revision $(inputs.params.buildRevision)"
  #     # sed -i "s#revision: \"[a-zA-Z0-9]\\+\"#revision: \"$(inputs.params.buildRevision)\"#" coffee-shop.yaml barista.yaml


  - name: update-yaml
    image: argoproj/argo-cd-ci-builder:v1.0.0
    workingDir: "$(workspaces.config-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      cd spring-petclinic-app/kubernetes/overlays/$(inputs.params.environment)/cd/resources

      echo "updating $(inputs.params.environment) image to $(inputs.params.appImage):$(inputs.params.imageDigest)"
      # sed -i "s#$(inputs.params.appImage):[a-zA-Z0-9]\\+#$(inputs.params.appImage):$(inputs.params.imageDigest)#" coffee-shop.yaml
      # pwd 
      # ls

      kustomize edit set image $(inputs.params.appImage)@$(inputs.params.imageDigest)

      # sed -i "s#newTag:[a-zA-Z0-9]\\+#newTag:$(inputs.params.imageDigest)#" kustomization.yaml
      # cat kustomization.yaml
      # echo "updating all pods in $(inputs.params.environment) to revision $(inputs.params.buildRevision)"
      # sed -i "s#revision: \"[a-zA-Z0-9]\\+\"#revision: \"$(inputs.params.buildRevision)\"#" coffee-shop.yaml barista.yaml


  - name: commit-push-changes-gitops
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.config-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      cd spring-petclinic-app
      git config --global user.email "samarsinghal@gmail.com"
      git config --global user.name "samarsinghal"
      git add .
      git commit --allow-empty -m "[tekton] updating $(inputs.params.environment) image to $(inputs.params.appImage):$(inputs.params.imageDigest)"
      # eval $(ssh-agent)
      # ssh-add ~/.ssh/id_*
      # git push origin master
      git push

  # - name: wait-for-argocd-rollout
  #   image: argoproj/argocd:v1.7.7
  #   script: |
  #     #!/usr/bin/env sh
  #     set -e

  #     argocd app sync $(inputs.params.argoAppName) --insecure
  #     argocd app wait $(inputs.params.argoAppName) --sync --health --operation --insecure
---