
namePrefix: spring-petclinic-
commonLabels:
  app.kubernetes.io/name: spring-petclinic
images:
- digest: sha256:1c7f98dbad2bb7b254bb7275a0777cdb5af774b24b80493c5c96b76c50242082
  name: harbor.tanzu.frankcarta.com/apps/spring-petclinic
- name: repository-project/application:1.0.0
  newName: harbor.tanzu.frankcarta.com/apps/spring-petclinic
  newTag: latest
# configMapGenerator:
#   - name: spring-configmap  # naming convention in base use to mount the file to /config/application.properties in a persistent volume
#     files:
#       - ../../application/application.properties
#   - name: spring-configmap-env  # naming convention in base to load environment variables from a reference to this config map
#     envs:
#       - ../../application/env.properties
  # - buildService/image.yaml                 
resources:
- github.com/samarsinghal/spring-boot-web
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
