---
actions:
  to: kubernetes/overlays/local/kustomization.yaml
---
images:
  - name: repository-project/application:1.0.0  #used for Kustomize matching
    newName: samarsinghal/{{artifactId}}
    newTag: latest
# configMapGenerator:
#   - name: spring-configmap  # naming convention in base use to mount the file to /config/application.properties in a persistent volume
#     files:
#       - application.properties
#   - name: spring-configmap-env  # naming convention in base to load environment variables from a reference to this config map
#     envs:
#       - env.properties
resources:
  - ../base
# patches:
# - application/deployment-patch.yaml
