# ---
# actions:
#   to: kubernetes/overlays/dev/cd/resources/deployment.yaml
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{artifactId}}
#   labels:
#     app: {{artifactId}}
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: {{artifactId}}
#   template:
#     metadata:
#       labels:
#         app: {{artifactId}}
#     spec:
#       containers:
#         - name: app 
#           image: harbor.tanzu.frankcarta.com/{{artifactId}}/{{artifactId}}:latest
#           imagePullPolicy: IfNotPresent
#           ports:
#             - containerPort: 8080
#           envFrom:
#             - configMapRef:
#                 name: spring-configmap-env
#           livenessProbe:
#             httpGet:
#               path: /actuator/info
#               port: 8080
#           readinessProbe:
#             httpGet:
#               path: /actuator/health
#               port: 8080